### ISSUE TITLE
Sample creation failed when use the extension remotely

### ISSUE THREAD

**Issue by fangxiaoran** [intel/vscode-sample-browser#3]
I followed this [link](https://software.intel.com/content/www/us/en/develop/documentation/remote-vscode-development-on-linux/top.html), tried to create a oneAPI project remotely. I can see the oneAPI samples list after I connected to the remote Linux target. But when I clicked the "+" button to create the project remotely, VS showed a notification:

> Sample Creation failed: Error: Command failed: "\~/.oneapi-cli/oneapi-cli" create -s "cpp" "oneapi-samples-6785e4451d2b8e536532f35ba4414a657ea410/DirectProgramming/DPC++/DenseLinearAlgebra/vector-add" "~/oneapi/vector-add"

Is it related to this extension, How to solve this issue? Thanks.

**Comment by tingleby** [comment]
Thanks for the issue!

The notification you got was the command it was trying to run to create the sample for you. 
`~/.oneapi-cli/oneapi-cli" create -s "cpp" "oneapi-samples-6785e4451d2b8e536532f35ba4414a657ea410/DirectProgramming/DPC++/DenseLinearAlgebra/vector-add" "~/oneapi/vector-add"`

Do you have a oneAPI toolkit installed on the remote system?
Does the `~/oneapi/vector-add` directory exist on the system already?

**Comment by fangxiaoran** [comment]
> Do you have a oneAPI toolkit installed on the remote system?
> Does the `~/oneapi/vector-add` directory exist on the system already?

Yes & Yes.

I've installed oneAPI base toolkit on the remote system, and I can build and run sample projects using command line. The path also exists, otherwise the extension will report an error and stop you to the next step.

Thank you for your attention to my issue. Look forward to your reply.

**Comment by tingleby** [comment]
Thanks! If you are using the basekit, i would expect the `oneapi-cli` to be found in that installation
Did you follow the environment setup regarding remote usage with the toolkit, you would need setvars to be called during login. 

https://software.intel.com/content/www/us/en/develop/documentation/remote-vscode-development-on-linux/top.html

**Comment by fangxiaoran** [comment]
Thanks for your suggestion. The issue was solved and I think it's caused by environment variable setting.

I did set oneAPI environment variables in `/etc/profile` before, but it didn't take effect. Then I reset vars refer to [this](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Bash-Startup-Files), and it worked.
